import = ["~/.config/alacritty/catppuccin/catppuccin-frappe.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 16

normal = { family = "Hack Nerd Font", style = "Reagular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "BoldItalic" }


[window]
dynamic_padding = true
option_as_alt = "OnlyLeft"
startup_mode = "Fullscreen"
